### ISSUE TITLE
Docker-compose

### ISSUE THREAD

**Issue by paulmixxx** [Ignasiya/chtune-social#5]
Есть небольшие советы по улучшению конфига

```
version: "3.8"

services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:${PATH_ROOT}
    ports:
      - '8000:80' # надо дать возможность переопределять внешний порт 
                  # https://github.com/docker/docs/issues/6914#issuecomment-398818071
                  # в других местах писать не буду, но тоже рекомендую поправить
    networks:
      - app
    depends_on:
      - server

  server:
    build: ./docker # это в целом норм вариант и многие так делают, но я бы посоветовал сделать по-другому.
                    # можно собрать готовый образ и загрузить его в реджистри github
                    # тогда ты надежно зафиксируешь образ и проект будет работать и запускаться у всех одинаково
                    # в отличии от варианта со сборкой в момент разворачивания проекта
                    # + не нужно тратить время на сборку, как бонус
                    # https://docs.github.com/ru/packages/working-with-a-github-packages-registry/working-with-the-container-registry
    working_dir: ${PATH_ROOT}
    restart: unless-stopped
    tty: true
    volumes:
      - ./src:${PATH_ROOT}
      - ./docker/php.ini:/usr/local/etc/php/conf.d/php-custom.ini
    ports:
      - '3000:3000' # я так понимаю это для фронта, да?
                    # вообще в философии докера, нужно стараться следовать практике 1 процесс = 1 контейнер
                    # по-хорошему лучше вынести dev server фронта на отдельный сервис, который будет запускаться 
                    # в момент make up
                    # в итоге у тебя будет 2 сервиса front и back, каждый живет в своем контейнере
    networks:
      - app
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    volumes:
      - ./mysql:/var/lib/mysql # я как-то ловил проблему с пробросом данных в папку
                               # возможно, это уже поправили в новых версиях, но с тех пор отношусь с осторожностью
                               # сам сохраняю данные в именованных томах
                               # они точно работают без проблем
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "8006:3306"
    networks:
      - app

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - '1025:1025'
      - '8025:8025'
    networks:
      - app

networks:
  app:
    driver: bridge
```
